### ISSUE TITLE
Sqlite Database error: "SQLSTATE[HY000]: General error: 1 no such function: RAND"

### ISSUE THREAD

**Issue by GreyFlorence** [whitebearcode/typecho-bearhoney#1]
Database error after the theme change.

**Environment:**
BearHoney主题版本：v1.1.6.20240805[[更新日志](https://docs.whitebear.dev/index.php/archives/7/)]
PHP版本：7.4.33
网站服务器：Caddy/unknown
数据库：Pdo_SQLite[Version：3.34.1]
Typecho版本：1.2.1
User Agent信息：Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36

**Debug log:**
Typecho\Db\Adapter\SQLException: SQLSTATE[HY000]: General error: 1 no such function: RAND in /www/typecho/var/Typecho/Db/Adapter/Pdo.php:111
Stack trace:
#0 /www/typecho/var/Typecho/Db.php(391): Typecho\Db\Adapter\Pdo->query()
#1 /www/typecho/var/Typecho/Db.php(424): Typecho\Db->query()
#2 /www/typecho/usr/themes/bearhoney/core/General.php(273): Typecho\Db->fetchAll()
#3 /www/typecho/usr/themes/bearhoney/post.php(95): General::getRandomPosts()
#4 /www/typecho/var/Widget/Archive.php(1418): require_once('/www/typecho/us...')
#5 /www/typecho/var/Typecho/Router.php(99): Widget\Archive->render()
#6 /www/typecho/index.php(23): Typecho\Router::dispatch()
#7 {main}

**Comment by whitebearcode** [comment]
Hello GreyFlorence,
there may be some problems with SQLite. 
this problem will be fixed tonight:)
