### ISSUE TITLE
Database Query Error

### ISSUE THREAD

**Issue by zycwer** [whitebearcode/typecho-bearhoney#2]
当开启插件时，现实Database Query Error
主题版本：最新
php版本：8.1
网站服务器：采用vercel@php部署
数据库：pgsql pdo
typecho版本：1.2.1
这是报错信息
Typecho\Db\Adapter\SQLException: SQLSTATE[42703]: Undefined column: 7 ERROR:  column "extensionStatus" does not exist
LINE 1: SELECT *  FROM typecho_bearExtensionsList WHERE  ("extension...
                                                          ^
HINT:  Perhaps you meant to reference the column "typecho_bearextensionslist.extensionstatus". in /var/task/user/var/Typecho/Db/Adapter/Pdo.php:111
Stack trace:
#0 /var/task/user/var/Typecho/Db/Adapter/Pdo/Pgsql.php(54): Typecho\Db\Adapter\Pdo->query('SELECT *  FROM ...', Object(PDO), 1, 'SELECT', 'typecho_bearExt...')
#1 /var/task/user/var/Typecho/Db.php(391): Typecho\Db\Adapter\Pdo\Pgsql->query('SELECT *  FROM ...', Object(PDO), 1, 'SELECT', 'typecho_bearExt...')
#2 /var/task/user/var/Typecho/Db.php(424): Typecho\Db->query(Object(Typecho\Db\Query))
#3 /var/task/user/usr/plugins/BearHoneyCore/loadExtensions.php(40): Typecho\Db->fetchAll(Object(Typecho\Db\Query))
#4 /var/task/user/usr/plugins/BearHoneyCore/Plugin.php(22): require_once('/var/task/user/...')
#5 /var/task/user/var/Widget/Plugins/Edit.php(54): require_once('/var/task/user/...')
#6 /var/task/user/var/Widget/Plugins/Edit.php(313): Widget\Plugins\Edit->activate('BearHoneyCore')
#7 /var/task/user/var/Widget/Action.php(71): Widget\Plugins\Edit->action()
#8 /var/task/user/var/Typecho/Widget.php(155): Widget\Action->execute()
#9 /var/task/user/var/Typecho/Router.php(96): Typecho\Widget::widget('\\Widget\\Action', NULL, Array)
#10 /var/task/user/index.php(23): Typecho\Router::dispatch()
#11 /var/task/user/api/index.php(10): require_once('/var/task/user/...')
#12 {main}

**Comment by jkjoy** [comment]
看样子是没做数据库的兼容

**Comment by whitebearcode** [comment]
好的，这边看一下问题

**Comment by whitebearcode** [comment]
pgsql数据库查询的字段大小写问题
下个版本处理，感谢反馈。

**Comment by whitebearcode** [comment]
你好，这个问题在最新版本v1.1.8中已做处理
https://github.com/whitebearcode/typecho-bearhoney/releases/tag/v1.1.8
可直接覆盖最新版本(主题和插件都需要覆盖)进行升级
若还有问题请反馈
